version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sa"
  app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    profiles:
      - prod
